# Generated by Django 5.0.7 on 2024-07-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='type',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ability_1_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ability_1_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ability_2_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ability_2_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='egg_group_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='egg_group_2',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='gender_ratio',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='hires_image',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='name_chinese',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='name_english',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='name_french',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='name_japanese',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='sp_attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='sp_defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='species',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='sprite',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='thumbnail',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type_2',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
